### ISSUE TITLE
按角色配适概率（多人）排序感觉不太对

### ISSUE THREAD

**Issue by wang-hui** [tseflcz/artifacts-master#10]
![image](https://user-images.githubusercontent.com/11165280/189500108-e78d5e31-d78d-4f4b-97c8-df17fe1d5551.png)
![image](https://user-images.githubusercontent.com/11165280/189500172-ff46a252-1bf3-4c86-a760-88daccd7f0aa.png)
RT.
为什么上图右下角的两个三无千岩杯会比下图右下角三攻魔女花排序靠前呀？

**Comment by tseflcz** [comment]
因为这个是按角色适配概率排的，您可以详细了解一下概率的计算公式，项目中py文件夹的readme里有写，花因为太好出了所以考虑到主词条概率天然是比攻击杯要低的，目测是没什么问题，鼠标悬停于圣遗物页签上可以显示具体每个人的适配概率。
另外看这个样式您使用的应该是主项目分支https://github.com/ideless/artifact，我维护的这个分支https://tseflcz.github.io/artifacts-master/里加入了另外的评分方式也欢迎您尝试。

**Comment by tseflcz** [comment]
因为这个是按角色适配概率排的，您可以详细了解一下概率的计算公式，项目中py文件夹的readme里有写，花因为太好出了所以考虑到主词条概率天然是比攻击杯要低的，目测是没什么问题，鼠标悬停于圣遗物页签上可以显示具体每个人的适配概率。
另外看这个样式您使用的应该是主项目分支[https://github.com/ideless/artifact]，我维护的这个分支[https://tseflcz.github.io/artifacts-master/]里加入了另外的评分方式也欢迎您尝试。

**Comment by wang-hui** [comment]
感谢回复。
我看了下 readme 里边的 套装与主属性相关系数 表。
TenacityOfTheMillelith atkp 系数是 -2.88。这可以说是相当大的惩罚了。
不太明白为什么我上图的两个三无千岩杯排名会比较靠前。
我会尝试下你建议的分支。

再次感谢，祝中秋快乐 ^_^

**Comment by tseflcz** [comment]
emmm事实上那个套装与主属性相关系数只有我维护的那个分支中的主属性得分功能中会用到，你目前使用的角色适配概率是不会用到这个系数的。
角色适配概率根据每个角色适配概率计算，使用千岩的角色如心海等辅助角色有效词条非常少，所以刷出更好千岩杯的概率更小，所以角色适配概率排序更高，这样说应该比较好理解。所以角色适配概率排序反应的不是圣遗物本身的好坏，反应的是和已出角色的适配率。
如果您想了解圣遗物的评价可以尝试下圣遗物得分，我当时设计这个评分体系就是为了保留下一些现在没有角色使用但是趋势上未来可能会有用的圣遗物（如生命水套这种）。

**Comment by tseflcz** [comment]
另外，你倒是提醒我了，因为每个版本只出一两个新角色这个系数变化不太大，所以readme中的那个表好像好久没更新过了，最近出了草系还要更新一下这个readme，目前想了解具体套装惩罚系数可以参考/src/ys/data/artifacts/artifact_w.ts

**Comment by wang-hui** [comment]
谢谢回复。我有空的时候会去看一下~
