### ISSUE TITLE
文档中有两个链接有点小问题

### ISSUE THREAD

**Issue by Patrick-Ze** [tseflcz/artifacts-master#9]
感谢大佬开发的工具，非常好用，这下选圣遗物省事多了。今天我在看[文档](https://tseflcz.github.io/artifacts-master/tutorial/)的时候发现两个小问题，悄悄捉个虫

`
声明：本工具是基于ideless大佬所作工具的二次开发，教程及界面均沿用原工具，原工具也非常好用，可至[原贴地址](https://bbs.nga.cn/read.php?tid=29551863) | [原项目地址](https://github.com/tideless/artifact) 查看。 本项目基于个人使用优化，具体优内容化可以至[项目地址](https://github.com/tseflcz/artifact-master)查看，有任何问题也可以提交issue反馈。
`

上面的**原项目地址**和**项目地址**两个链接都是打不开的，可能需要更新：
原项目地址可能需要更正为 `https://github.com/ideless/artifact`
项目地址可能需要更正为`https://github.com/tseflcz/artifacts-master`

**Comment by tseflcz** [comment]
感谢指正，说明文档之后也需要更新一下新功能的使用方法，等过段时间我有空一点再弄这个。

**Comment by Patrick-Ze** [comment]
文档已更新
